refactoring

diff --git a/scripts/hooks/pre-commit b/scripts/hooks/pre-commit
--- a/scripts/hooks/pre-commit
+++ b/scripts/hooks/pre-commit
@@ -1,5 +1,5 @@
 #!/bin/sh
-echo "Running pre-commit hooks"
+#echo "Running pre-commit hooks"
 
 PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
 STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
@@ -15,36 +15,35 @@ then
 fi
 SFILES=${SFILES:-$STAGED_FILES_CMD}
 
-echo "Auto Generating Jobs tests..."
-php artisan app:generate-jobs-tests >&1
-if [ $? -ne 0 ]
-then
-    echo "Error generating Jobs tests. Please fix the issue before commit."
-    exit 1
-fi
-
-echo "Auto Generating Modules Jobs tests..."
-php artisan app:generate-modules-tests >&1
-if [ $? -ne 0 ]
-then
-    echo "Error generating Modules Jobs tests. Please fix the issue before commit."
-    exit 1
-fi
-
-echo "Auto Generating Web Routes Jobs tests..."
-php artisan app:generate-routes-tests >&1
-if [ $? -ne 0 ]
-then
-    echo "Error generating Web Routes Jobs tests. Please fix the issue before commit."
-    exit 1
-fi
+#echo "Auto Generating Jobs tests..."
+#php artisan app:generate-jobs-tests >&1
+#if [ $? -ne 0 ]
+#then
+#    echo "Error generating Jobs tests. Please fix the issue before commit."
+#    exit 1
+#fi
+#
+#echo "Auto Generating Modules Jobs tests..."
+#php artisan app:generate-modules-tests >&1
+#if [ $? -ne 0 ]
+#then
+#    echo "Error generating Modules Jobs tests. Please fix the issue before commit."
+#    exit 1
+#fi
+#
+#echo "Auto Generating Web Routes Jobs tests..."
+#php artisan app:generate-routes-tests >&1
+#if [ $? -ne 0 ]
+#then
+#    echo "Error generating Web Routes Jobs tests. Please fix the issue before commit."
+#    exit 1
+#fi
 
 echo "Running PHPUnit tests..."
 for FILE in $SFILES
 do
     FILE_NAME=$(basename "$FILE" .php)
 
-#    echo "Executing: vendor/bin/phpunit --stop-on-failure --filter \"$FILE_NAME\""
     vendor/bin/phpunit --stop-on-failure --filter "$FILE_NAME" >&1
     if [ $? -ne 0 ]
     then
@@ -52,7 +51,6 @@ do
         exit 1
     fi
 
-#    echo "Executing: php artisan dusk --stop-on-failure --stop-on-error --filter \"$FILE_NAME\""
     php artisan dusk --stop-on-failure --stop-on-error --filter "$FILE_NAME" >&1
     if [ $? -ne 0 ]
     then
@@ -60,18 +58,15 @@ do
         exit 1
     fi
 
-    FILES="$FILES $PROJECT/$FILE"
-done
 
-echo "Checking PHP Lint..."
-for FILE in $SFILES
-do
+    echo "Checking PHP Lint..."
     php -l -d display_errors=0 $FILE >&1
     if [ $? -ne 0 ]
     then
         echo "Fix the error before commit."
         exit 1
     fi
+
     FILES="$FILES $PROJECT/$FILE"
 done
 
