test

diff --git a/scripts/hooks/pre-commit b/scripts/hooks/pre-commit
--- a/scripts/hooks/pre-commit
+++ b/scripts/hooks/pre-commit
@@ -14,6 +14,18 @@ then
 fi
 SFILES=${SFILES:-$STAGED_FILES_CMD}
 
+echo "Running PHPUnit tests..."
+for FILE in $SFILES
+do
+    vendor/bin/phpunit --stop-on-failure --filter "$FILE"
+    if [ $? != 0 ]
+    then
+        echo "Fix the error before commit."
+        exit 1
+    fi
+    FILES="$FILES $PROJECT/$FILE"
+done
+
 echo "Checking PHP Lint..."
 for FILE in $SFILES
 do
