refactoring

diff --git a/scripts/hooks/pre-commit b/scripts/hooks/pre-commit
--- a/scripts/hooks/pre-commit
+++ b/scripts/hooks/pre-commit
@@ -31,9 +31,19 @@ do
 
 #    echo "Executing: vendor/bin/phpunit --stop-on-failure --filter \"$FILE_NAME\""
     vendor/bin/phpunit --stop-on-failure --filter "$FILE_NAME" >&1
+    if [ $? -ne 0 ]
+    then
+        echo "PHPUnit tests failed. Please fix the issue before commit."
+        exit 1
+    fi
 
 #    echo "Executing: php artisan dusk --stop-on-failure --stop-on-error --filter \"$FILE_NAME\""
     php artisan dusk --stop-on-failure --stop-on-error --filter "$FILE_NAME" >&1
+    if [ $? -ne 0 ]
+    then
+        echo "Dusk tests failed. Please fix the issue before commit."
+        exit 1
+    fi
 
     FILES="$FILES $PROJECT/$FILE"
 done
@@ -42,6 +52,11 @@ echo "Checking PHP Lint..."
 for FILE in $SFILES
 do
     php -l -d display_errors=0 $FILE >&1
+    if [ $? -ne 0 ]
+    then
+        echo "Fix the error before commit."
+        exit 1
+    fi
     FILES="$FILES $PROJECT/$FILE"
 done
 
@@ -49,6 +64,11 @@ if [ "$FILES" != "" ]
 then
     echo "Running Code Sniffer. Code standard PSR2."
     ./vendor/bin/phpcs --encoding=utf-8 -n -p $FILES >&1
+    if [ $? -ne 0 ]
+    then
+        echo "Fix the error before commit."
+        exit 1
+    fi
 fi
 
 exit $?
